Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### client VM ###
  config.vm.define "client01" do |client01|
    client01.vm.box = "ubuntu/jammy64"
    client01.vm.hostname = "client01"
    client01.vm.network "private_network", ip: "192.168.0.11"
    client01.vm.provision "shell", path: "client01.sh", privileged: false

  end
  
### server vm ###
   config.vm.define "server01" do |server01|
    server01.vm.box = "ubuntu/jammy64"
    server01.vm.hostname = "server01"
    server01.vm.network "private_network", ip: "192.168.0.22"
    server01.vm.provision "shell", path: "server01.sh", privileged: false
  
   end
   
### mysql vm  ####
  config.vm.define "mysql01" do |mysql01|
    mysql01.vm.box = "ubuntu/jammy64"
	  mysql01.vm.hostname = "mysql01"
    mysql01.vm.network "private_network", ip: "192.168.0.33"
    mysql01.vm.provision "shell", path: "mysql01.sh", privileged: false
  end

# ### nginx vm  ####
#   config.vm.define "nginx01" do |nginx01|
#     nginx01.vm.box = "ubuntu/jammy64"
#     nginx01.vm.hostname = "nginx01"
#     nginx01.vm.network "private_network", ip: "192.168.0.44"
#     nginx01.vm.provision "shell", path: "nginx01.sh", privileged: false
#   end
  
end
