Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### client VM ###
  config.vm.define "client01" do |client01|
    client01.vm.box = "ubuntu/jammy64"
    client01.vm.hostname = "client01"
    client01.vm.network "private_network", ip: "192.168.56.11"
  end
  
### server vm ###
   config.vm.define "server01" do |server01|
    server01.vm.box = "ubuntu/jammy64"
    server01.vm.hostname = "server01"
    server01.vm.network "private_network", ip: "192.168.56.12"
  
   end
   
### mysql vm  ####
  config.vm.define "mysql01" do |mysql01|
    mysql01.vm.box = "ubuntu/jammy64"
	  mysql01.vm.hostname = "mysql01"
    mysql01.vm.network "private_network", ip: "192.168.56.16"
  end
  
end
