---
- hosts: all
  become: true
  tasks:
    - name: install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install apache openjdk-17-jre
      ansible.builtin.apt:
        name: openjdk-17-jre
        state: present

    - name: install docker
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh ./get-docker.sh
        exit 0

    - name: Create group docker
      group:
        name: docker
        state: present

    - name: Add the user jenkins with a specific uid and a primary group of docker
      ansible.builtin.user:
        name: ubuntu
        state: present
        group: docker

    - name: restart service docker
      ansible.builtin.service:
        name: docker
        state: restarted
