---
- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      update_cache: yes
    changed_when: false

- hosts: workstations
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip
      state: latest

  # - name: install terraform
  #   ansible.builtin.unarchive:
  #     src: https://releases.hashicorp.com/terraform/1.9.1/terraform_1.9.1_darwin_amd64.zip
  #     dest: /usr/local/bin
  #     remote_src: yes
  #     mode: 0755
  #     owner: root
  #     group: root

- hosts: web_servers
  become: true
  tasks:
  - name: install packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
  - name: copy default html file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: true


- hosts: db_servers
  become: true
  tasks:
  - name: install mariabd package (ubuntu)
    apt:
      name: mariadb-server
      state: latest